import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import re
from datetime import datetime

# --- 1. CONFIGURATION ---
st.set_page_config(layout="wide", page_title="UK FC Picking Velocity Map")

# --- 2. DATA SOURCES ---
# New Spreadsheet ID for Picking Data
SHEET_ID = "1uKo-jej2UlA-cdhgYFWS9CqQ5h0uqcxLi-BSp-V1V6o"
RAW_URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/gviz/tq?tqx=out:csv&sheet=RAW"

st.sidebar.title("🏃 Picking Navigation")

@st.cache_data(ttl=10)
def load_picking_data():
    t = datetime.now().timestamp()
    df_raw = pd.read_csv(f"{RAW_URL}&t={t}")
    # Load the same layout file
    df_bp = pd.read_csv('master_blueprint.csv')
    
    # Standardize column headers
    df_raw.columns = df_raw.columns.str.strip().str.replace(' ', '_').str.lower()
    return df_bp, df_raw

try:
    df_blueprint, df_raw_data = load_picking_data()

    def sanitize(text):
        return re.sub(r'[^A-Z0-9]', '', str(text).upper())

    # --- 3. FILTERS ---
    client_list = ["All Clients"] + sorted(df_raw_data['client_name'].dropna().unique().tolist())
    selected_client = st.sidebar.selectbox("Filter by Client", client_list)
    
    level_options = ["Level 1", "Level 2", "Level 3", "Level 4", "Level 5"]
    selected_level = st.sidebar.selectbox("Select Floor View", level_options)

    # Filter Data by Client
    if selected_client != "All Clients":
        df_filtered = df_raw_data[df_raw_data['client_name'] == selected_client].copy()
    else:
        df_filtered = df_raw_data.copy()

    # --- 4. CALCULATION: PICK VELOCITY ---
    # Count how many times each BAY was visited
    df_filtered['bay_key'] = df_filtered['bay'].apply(sanitize)
    bay_counts = df_filtered['bay_key'].value_counts().to_dict()
    
    # Count how many times each specific LOCATION was visited
    location_rank = df_filtered['location'].value_counts().reset_index()
    location_rank.columns = ['Location', 'Picks']

    # --- 5. GRID MAPPING ---
    df_lvl_bp = df_blueprint[df_blueprint['level'].astype(str).str.contains(selected_level, case=False)].copy()
    
    if df_lvl_bp.empty:
        st.error(f"No coordinates found for {selected_level}")
    else:
        max_r, max_c = int(df_lvl_bp['grid_row'].max() + 1), int(df_lvl_bp['grid_col'].max() + 1)
        # We use zeros as a baseline for frequency
        color_grid = np.full((max_r, max_c), np.nan)
        
        for _, row in df_lvl_bp.iterrows():
            r, c = int(row['grid_row']), int(row['grid_col'])
            m_key = sanitize(row['bay_name'])
            # The value is the number of picks in that bay
            color_grid[r, c] = bay_counts.get(m_key, 0)

        # --- 6. VISUALIZATION: HEATMAP ---
        st.title(f"Picking Velocity: {selected_level} ({selected_client})")
        
        fig, ax = plt.subplots(figsize=(25, 12), facecolor='none')
        ax.set_facecolor('none')
        
        # Color Map: Green (Low Picks) -> Yellow -> Red (High Picks)
        cmap = mcolors.LinearSegmentedColormap.from_list("", ["#2ecc71", "#f1c40f", "#e74c3c"])
        
        sns.heatmap(
            color_grid, 
            cmap=cmap, 
            cbar=True, # Show the scale of picks
            linewidths=0.5, 
            linecolor='black', 
            mask=np.isnan(color_grid), 
            ax=ax
        )

        # Draw labels
        processed_labels = set()
        for _, row in df_lvl_bp.iterrows():
            r, c = int(row['grid_row']), int(row['grid_col'])
            clean_label = re.sub(r'\d+$', '', str(row['bay_name'])).rstrip('-').strip()
            if f"{clean_label}_{c}" not in processed_labels:
                ax.text(c + 0.5, r - 0.7, clean_label, ha='center', va='bottom', color='#888888', weight='bold', fontsize=10)
                processed_labels.add(f"{clean_label}_{c}")

        plt.axis('off')
        st.pyplot(fig, use_container_width=True)

        # --- 7. TOP LOCATIONS LIST ---
        st.markdown("---")
        st.subheader(f"🏆 Most Visited Locations ({selected_client})")
        
        col1, col2 = st.columns([1, 2])
        with col1:
            st.write("Top 15 Specific Spots")
            st.dataframe(location_rank.head(15), use_container_width=True, hide_index=True)
            
        with col2:
            total_picks = df_filtered.shape[0]
            st.info(f"Total picks for this selection: **{total_picks}**")
            st.write("This data is generated by counting unique entries in the RAW tab for the selected filters.")

except Exception as e:
    st.error(f"Error loading picking data: {e}")
